"use client";

import React from "react";

export default function TermsAndConditions() {
  return (
    <div className="bg-white text-gray-800">
      {/* Header */}
      <div className="bg-gradient-to-r from-orange-300 via-white to-green-300 text-white py-16 px-4 text-center shadow-lg">
        <h1 className="text-4xl font-bold mb-2 text-blue-800">Terms & Conditions</h1>
        <p className="text-lg text-blue-800 font-semibold max-w-2xl mx-auto">
          Please read these terms and conditions carefully before using our services.
        </p>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-10">
        <div className="space-y-8 text-gray-700 text-base leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Terms</h2>
            <p>
            This document is an electronic record in terms of the amended Information Technology Act, 2000 and rules and regulation made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the Terms for access or usage of Majhi Navi Mumbai’s service via Majhi Navi Mumbai Portal. This document meets the stipulations and conditions mentioned in Section 65B (2) of the Indian Evidence Act, 1872.
            </p>
            <p>This is an agreement between Majhi Navi Mumbai Ltd., a company incorporated under the Companies Act 1956 with its registered office at Building M, 501-B, Palm Court Complex, Besides Goregaon Sports Club, New Link Road, Malad (W), Mumbai 400 064, the owner and operator of www.Majhi Navi Mumbai.com (the "Majhi Navi Mumbai Site"), the Majhi Navi Mumbai Application Software "Majhi Navi Mumbai Mobile App", including collectively, including all content provided by Majhi Navi Mumbai through Majhi Navi Mumbai Application and the Majhi Navi Mumbai Site, the "Majhi Navi Mumbai Service", or the "Service", and you ("you" or "You"), a user of the Service. BY USING THE SERVICE, YOU ACKNOWLEDGE AND AGREE TO THESE TERMS OF SERVICE,<span className="text-blue-500"> TERMS OF USE FOR SEARCH PLUS SERVICES, INFRINGEMENT POLICY, COUNTERFEIT & PRIVACY PREVENTION POLICY, Contest and Refer & Earn program terms, SOFTWARE LICENSE AGREEMENT, HOSTING SERVICES AGREEMENT, SOFTWARE LICENSE AND HOSTING AGREEMENT, UPI TERMS , JD PAY (Receiver), JD PAY (Sender), Service For Listing, Majhi Navi Mumbai Messenger, Terms for Digital Catalogue-B2B, Reseller Terms, Terms of use for Real Estate, Terms Of Use For Information Dissemination, TERMS & CONDITIONS (JD OMNI), Terms and conditions for JDRR CERTIFICATE, JD Shopping Terms and Condition, JD Shopping Return Policy, TERMS OF SERVICE FOR JD CASH PROGRAM, Terms For KYC </span> AND MAJHI NAVI MUMBAI'S PRIVACY POLICY, WHICH CAN BE FOUND AT <span className="text-blue-500">PRIVACY POLICY</span>  AND WHICH ARE INCORPORATED HEREIN BY REFERENCE. If you choose to not agree with any of these terms, you may not use the Service.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Majhi Navi Mumbai Service:</h2>
            <p>These Terms of Service apply to all users of the Majhi Navi Mumbai Service. Information provided by our users through the Majhi Navi Mumbai Service may contain links to third party websites that are not owned or controlled by Majhi Navi Mumbai. Majhi Navi Mumbai has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. Also, Majhi Navi Mumbai does not assume any liability for any mistakes, misstatements of law, defamation, omissions, falsehood, obscenity, pornography or profanity in the statements, opinions, representations or any other form of third party content on the Site. In addition, Majhi Navi Mumbai will not and cannot censor or edit the content of any third-party site. By using the Service, you expressly acknowledge and agree that Majhi Navi Mumbai shall not be responsible for any damages, claims or other liability arising from or related to your use of any third-party website. You understand that the information and opinions in the third party content represent solely the thoughts of the author and is neither endorsed by nor does it necessarily reflect Majhi Navi Mumbai's belief.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Errors, Corrections, and Right to Modify or Discontinue Service and Sites:</h2>
           <p>We do not represent or warrant that the Majhi Navi Mumbai Site will be error-free, free of viruses or other harmful components, or that defects will be corrected. We do not represent or warrant that the information available on or through the Majhi Navi Mumbai Site will be correct, accurate, timely or otherwise reliable. We may make changes to the features, functionality or content of the Majhi Navi Mumbai Site at any time. We reserve the right in our sole discretion to edit or delete any documents, information or other content appearing on the Site. Majhi Navi Mumbai reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Services and/or Sites (or any part thereof) with or without notice. Majhi Navi Mumbai shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service or any Sites.</p>
           </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Majhi Navi Mumbai Access:</h2>
            <p>
            <span className="font-bold">A.</span> . Subject to your compliance with these Terms of Service, Majhi Navi Mumbai hereby grants you permission to use the Service, provided that:
            </p>
            <ul className="list-[lower-roman] px-6 marker:font-bold pl-6 space-y-4">
              <li>your use of the Service as permitted is solely for your personal use, and you are not permitted to resell or charge others for use of or access to the Service, or in any other manner inconsistent with these Terms of Service;</li>
              <li>you will not duplicate, transfer, give access to, copy or distribute any part of the Service in any medium without Majhi Navi Mumbai's prior written authorization;</li>
              <li>you will not attempt to reverse engineer, alter or modify any part of the Service;</li>
              <li>you will otherwise comply with the terms and conditions of these Terms of Service and Privacy Policy. The Application is currently made available to you free of charge for your personal, non-commercial use. Majhi Navi Mumbai reserves the right to amend or withdraw the Application, or charge for the application or service provided to you in accordance with these Majhi Navi Mumbai Mobile App terms, at any time and for any reason.</li>
              </ul>
            <p><span className="font-bold">B.</span> In order to access and use the features of the Service, you acknowledge and agree that you will have to provide Majhi Navi Mumbai with your mobile phone number. You expressly acknowledge and agree that in order to provide the Service, Majhi Navi Mumbai may periodically access your contact list and/or address book on your mobile device to find and keep track of mobile phone numbers of other users of the Service. When providing your mobile phone number, you must provide accurate and complete information. You hereby give your express consent to Majhi Navi Mumbai to access your contact list and/or address book for mobile phone numbers in order to provide and use the Service. We do not collect addresses or email addresses, just names and mobile phone numbers to tag your friends (as defined in Privacy Policy) and view their ratings (as defined in Privacy Policy) given to businesses listed with Majhi Navi Mumbai. You must notify Majhi Navi Mumbai immediately of any breach of security or unauthorized use of your mobile phone. For removal of doubts it is clarified that, Majhi Navi Mumbai is not liable for any loss or damage caused by any unauthorized use of your account, however you would be liable for any losses or damage caused to Majhi Navi Mumbai including but not limited to any claims made on Majhi Navi Mumbai or others due to such unauthorized use.</p>
            <p><span className="font-bold">C.</span> You agree not to use or upload, post or submit any content that contains software viruses or any computer code, files, or programs designed to interrupt, destroy, or limit functionality of the Application or of any computer software, hardware, or telecommunications equipment. You also agree to not decipher, decompile, disassemble, use sniffers (except Ethereal, tcpdump or HTTPWatch in general) or reverse engineer any of the software comprising or in any way making up part of the Application. We have to disallow use of request modification tools such as fiddler or whisker, or the like or any other such tools activities that are meant to explore or harm, penetrate or test the application. You must secure our permission before you measure, test, health check or otherwise monitor any network equipment, servers or assets hosted on our domain. You agree not to collect or harvest any personally identifiable information, including phone number, from the Service, nor to use the communication systems provided by the Service for any commercial solicitation or spam purposes. You agree not to spam, or solicit for commercial purposes, any users of the Service. You agree not to create any data back up of the content that is available to you by use of the Majhi Navi Mumbai Site or Majhi Navi Mumbai Mobile App. or use of Majhi Navi Mumbai Service that is available through any other mediums.</p>
           
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">AVAILABILITY:</h2>
           <ul className="list-decimal marker:font-bold pl-6 space-y-4">
            <li>Majhi Navi Mumbai will use reasonable efforts to make the Application available at all times. However you acknowledge the Application is provided over the internet and mobile networks and so the quality and availability of the Application may be affected by factors outside Majhi Navi Mumbai reasonable control.</li>
            <li>Majhi Navi Mumbai does not accept any responsibility whatsoever for unavailability of the Application, or any difficulty or inability to download or access content or any other communication system failure which may result in the Application being unavailable.</li>
            <li>Majhi Navi Mumbai will not be responsible for any support or maintenance for the Application.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">SYSTEM REQUIREMENTS:</h2>
            <ul className="list-decimal marker:font-bold pl-6 space-y-4">
            <li>In order to use the Application, you are required to have a compatible mobile telephone or handheld device, internet access, and the necessary minimum specifications ('Software Requirements').</li>
            <li>The Software Requirements for downloading the Majhi Navi Mumbai Mobile App would vary as per the mobile platform. The Majhi Navi Mumbai Mobile App would be available in English Language as of now.</li>
            <li>The version of the Application software may be upgraded from time to time to add support for new functions and services.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Intellectual Property Rights:</h2>
           <p>The Majhi Navi Mumbai company names, logos, all related products and service names, design marks, slogans, trademarks, service marks, copyright, database rights (and other intellectual property rights of any nature in the Application) together with the underlying software code in the App ("Intellectual Property") is owned by and used under license by Majhi Navi Mumbai or its subsidiaries or affiliate companies. All other Intellectual Properties herein are the property of their respective owners. All copies that you make of the Materials on any of the Media must bear any copyright, trademark or other proprietary notice located on the respective Media that pertains to the material being copied. You are not authorized to use Majhi Navi Mumbai's Intellectual Property in any advertising, publicity or in any other commercial manner. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by Majhi Navi Mumbai.
            </p>
            <p>For removal of doubts, it is clarified that, by accepting theses terms, you hereby waive and grant to Majhi Navi Mumbai all rights including intellectual property rights and also "moral rights" in the Reviews, Ratings and Comments posted by you at Majhi Navi Mumbai through any of mediums of Majhi Navi Mumbai and that Majhi Navi Mumbai is free to use all such Review, Ratings and Comments as per its (Majhi Navi Mumbai's) requirements from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">User Submissions & Specific Features:</h2>
          <ul className="list-[upper-alpha] marker:font-bold pl-6 space-y-4">
            <li>Tag your Friends - (Refer Privacy Policy)</li>
            <li> Ratings and Reviews - (Refer Privacy Policy)</li>
            <li>In connection with Ratings and Tag your friends, you further agree that you will not: </li>
          
          <ul className="list-[lower-roman] marker:font-bold pl-6 space-y-4">
            <li>submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Majhi Navi Mumbai all of the license rights granted herein;</li>
            <li>publish falsehoods or misrepresentations that could damage Majhi Navi Mumbai or any third party;</li>
            <li>submit material that is unlawful, obscene, defamatory, libelous, threatening, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate;</li>
            <li>post advertisements or solicitations of business;</li>
            <li>impersonate another person; business;</li>
            <li>send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs;</li>
            <li>interfere with or disrupt the integrity or performance of the Service or the data contained therein; or </li>
            <li>attempt to gain unauthorized access to the Service or its related systems or networks.</li>

          </ul>
          <li>Adult content must be identified as such. Majhi Navi Mumbai does not endorse any Rating and/or Review or any opinion, recommendation, or advice expressed therein, and Majhi Navi Mumbai expressly disclaims any and all liability in connection with ratings and/or submissions. Majhi Navi Mumbai does not permit copyright infringing activities and infringement of intellectual property rights via its Service, and Majhi Navi Mumbai will remove all content and Ratings and/or Reviews if properly notified that such content infringes on another's intellectual property rights. To file a copyright infringement notification, please send a written communication that includes substantially the following:</li>
          

          <ul className="list-[lower-roman] marker:font-bold pl-6 space-y-4">
            <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
            <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works;</li>
            <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material, including the mobile phone number of the Majhi Navi Mumbai Mobile App user allegedly infringing the copyrighted work;</li>
            <li>Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</li>
            <li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. Such takedown notices may be emailed to support at. Majhi Navi Mumbai reserves the right to remove contents without prior notice. Majhi Navi Mumbai may also terminate a user's access to the Service, if they are determined to be a repeat infringer, or for any or no reason, including being annoying. A repeat infringer is a User who has been notified of infringing activity more than once and/or has had a content removed from the Service more than once. Majhi Navi Mumbai also reserves the right to decide whether content or a Rating and/or Review is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to excessive length or limited interest. Majhi Navi Mumbai may remove such contents and/or terminate a User's access for uploading such material in violation of these Terms of Service at any time, without prior notice and at its sole discretion.</li>
          </ul>
          <li>You understand that when using the Majhi Navi Mumbai Service you will be exposed to Ratings and Review submissions from a variety of sources, and that Majhi Navi Mumbai is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Submissions, and that such Submissions are not the responsibility of Majhi Navi Mumbai. You further understand and acknowledge that you may be exposed to Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Majhi Navi Mumbai with respect thereto, and agree to indemnify and hold Majhi Navi Mumbai, its officers, directors, employees, agents, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the Majhi Navi Mumbai Service.</li>
          <li>Majhi Navi Mumbai reserves the right to discontinue any aspect of the Majhi Navi Mumbai Service at any time.</li>
          <li>Right, But Not Obligation, to Monitor Submissions: Majhi Navi Mumbai does not and shall not have any obligation to review Submissions, and therefore we do not guarantee the accuracy, integrity or quality of Submissions and we cannot assure you that harmful, inaccurate, deceptive, offensive, threatening, defamatory, unlawful or otherwise objectionable Submissions will not appear on our Service. We do, however, reserve the right to review any or all Submissions in our sole discretion. In addition, we reserve the right to alter, edit or remove any Submissions, in whole or in part, at our sole discretion.</li>
          <li>Your Use of Submissions Posted by Others. You may not use, copy, reproduce, distribute, publish, display or perform, create derivative works of, transmit, sell, or in any way exploit any of the Submissions posted by others except as expressly set forth in these Terms of Use.</li>
          </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">WARRANTY:</h2>
            <p>
              THE MATERIAL AND THE MEDIA USED TO PROVIDE THE MATERIAL (INCLUDING THE WEBSITE ) ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. Majhi navi Mumbai DISCLAIMS, TO THE FULLEST EXTENT PERMITTED UNDER LAW, ANY WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY AND PERFORMANCE OF THE MEDIA AND MATERIALS. Majhi navi Mumbai DOES NOT WARRANT THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE CONTENT IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Majhi navi Mumbai DISCLAIMS ANY AND ALL WARRANTIES TO THE FULLEST EXTENT OF THE LAW, INCLUDING ANY WARRANTIES FOR ANY INFORMATION, GOODS, OR SERVICES, OBTAINED THROUGH, ADVERTISED OR RECEIVED THROUGH ANY LINKS PROVIDED BY OR THROUGH THE MEDIA. SOME COUNTRIES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM COUNTRY TO COUNTRY AND JURISDICTION TO JURISDICTION. IN NO EVENT SHALL JUSTDIAL BE LIABLE TO ANY USER ON ACCOUNT OF SUCH USER'S USE, MISUSE OR RELIANCE ON THE MEDIA FOR ANY DAMAGES WHATSOEVER, INCLUDING DIRECT, SPECIAL, PUNITIVE, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR DAMAGES FOR LOSS OF PROFITS, REVENUE, USE, OR DATA WHETHER BROUGHT IN WARRANTY, CONTRACT, INTELLECTUAL PROPERTY INFRINGEMENT, TORT (INCLUDING NEGLIGENCE) OR OTHER THEORY, EVEN IF JUSTDIAL IS AWARE OF OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, ARISING OUT OF OR CONNECTED WITH THE USE (OR INABILITY TO USE) OR PERFORMANCE OF THE MEDIA OR THE USE (OR INABILITY TO USE), RELIANCE UPON OR PERFORMANCE OF ANY MATERIAL CONTAINED IN OR ACCESSED FROM ANY MEDIA. JUSTDIAL DOES NOT ASSUME ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT OR PROCESS DISCLOSED ON THE MEDIA OR OTHER MATERIAL ACCESSIBLE FROM THE MEDIA. THE USER OF THE MEDIA ASSUMES ALL RESPONSIBILITY AND RISK FOR THE USE OF THIS MEDIA. THE FOREGOING LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. SOME COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY OF CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO ALL USERS; IN SUCH COUNTRIES LIABILITY IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">ADDITIONAL DISCLAIMER:</h2>
            <p>
            Users using any of Majhi Navi Mumbai service across the following mediums i.e. through internet i.e. www.justdial.com Website, Wapsite, SMS, phone or any other medium are bound by this additional disclaimer wherein they are cautioned to make proper enquiry before they (Users) rely, act upon or enter into any transaction (any kind or any sort of transaction including but not limited to monetary transaction) with the Advertiser listed with Majhi Navi Mumbai. All the Users are cautioned that all and any information of whatsoever nature provided or received from the Advertiser/s is taken in good faith, without least suspecting the bonafides of the Advertiser/s and Majhi Navi Mumbai does not confirm, does not acknowledge, or subscribe to the claims and representation made by the Advertiser/s listed with Majhi Navi Mumbai. Further, Majhi Navi Mumbai is not at all responsible for any act of Advertiser/s listed at Majhi Navi Mumbai.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Limitation of Liability</h2>
            <p>
            IN NO EVENT SHALL Majhi Navi Mumbai, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY
            </p>
            <ul className="list-[upper-roman] marker:font-bold pl-6 space-y-4">
              <li>ERRORS, MISTAKES, OR INACCURACIES OF CONTENT,</li>
              <li>PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE,</li>
              <li>ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN,</li>
              <li>ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVERS,</li>
              <li>ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY,</li>
              <li>ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE JUSTDIAL CLIENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND/OR</li>
              <li>THE DISCLOSURE OF INFORMATION PURSUANT TO THESE TERMS OF SERVICE OR PRIVACY POLICY. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</li>
            </ul>
            <p>YOU SPECIFICALLY ACKNOWLEDGE THAT Majhi Navi Mumbai SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Indemnity:</h2>
            <p>
            You agree to defend, indemnify and hold harmless Majhi Navi Mumbai officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from:
            </p>
            <ul className="list-[lower-roman] marker:font-bold pl-6 space-y-4">
              <li>your use of and access to the Majhi Navi Mumbai Service;</li>
              <li>your violation of any term of these Terms of Service;</li>
              <li>your violation of any third party right, including without limitation any copyright, property, or privacy right; or</li>
              <li>any claim that one of your Ratings and/or Reviews or Comments caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the Majhi navi Mumbai Service.</li>
            </ul>
          </section>


          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Ability to Accept Terms of Service:</h2>
            <p>
            Majhi Navi Mumbai Service. Only adults, who are at least eighteen (18) years of age, are eligible to use our service, whether for personal use or on behalf of a business. If you are an individual, you must be fully competent to enter into and to comply with the terms, conditions, obligations, representations, and warranties set forth in these Terms of Use. By using this service, you represent and warrant that you have the right, authority, and capacity to enter into these Terms of Use and can abide by all of the terms and conditions set forth therein.
            </p>
          </section>


          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Assignment:</h2>
            <p>
            These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Majhi Navi Mumbai without restriction.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">Miscellaneous:</h2>
            <p>
            You agree that we may assign these Terms of Use without prior notice to a successor entity in the event of a merger, acquisition, or sale of all or part of our business. No waiver of any breach of the Terms of Use, no matter how long continuing or how often repeated will be deemed a waiver of any subsequent breach, nor shall any delay or omission to exercise any right, power, or privilege hereunder be deemed a waiver of such right, power, or privilege. If any section of these Terms of Use is held to be unenforceable or in conflict with the law of any jurisdiction, the validity of the remaining paragraphs shall not be affected by such holding. The meaning of that section shall be construed to the extent feasible to render the section enforceable and to give effect to the Parties' intentions as reflected in the section. If no feasible interpretation would save such section, it is to be severed from the remainder of these Terms of Use, which are to remain in full force and effect. The Terms of Use constitute the entire agreement between you and us with respect to the subject matter set forth herein. The section headings and subheadings contained in these Terms of Use are included for convenience only and shall not limit or otherwise affect these Terms of Use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-3 text-blue-700">GOVERNING LAW:</h2>
            <p>
            These Terms will be governed by and construed in accordance with the Indian laws, without giving effect to its conflict of laws' provisions or your actual state or country of residence, and you agree to submit to personal jurisdiction in India. Courts at Mumbai will have the exclusive jurisdiction. You are responsible for compliance with applicable laws. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect. Majhi Navi Mumbai reserves the right to investigate complaints or reported violations of these Terms and to take any action we deem necessary and appropriate. Such action may include reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties. In addition, we may take action to disclose any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. Majhi Navi Mumbai reserves the right to seek all remedies available at law and in equity for violations of these Terms.
            </p>
          </section>
         
        </div>
      </div>
    </div>
  );
}
